name: Testing

# Remember to detect on prerelease which is a subtype
on: [push, pull_request, release]

# These are going to be our jenkins.yml file
env:
  slack_channel: undefined
  checkmarx_fail_severity: undefined
  checkmarx_warn_severity: undefined
  snyk_fail_severity: undefined
  checkmarx_all_pull_requests: undefined
  app_node_all: undefined
  before_deploy: undefined
  run_front_end_test: false

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      version: 1
    steps:
      - uses: actions/checkout@v1
      - name: Run a script
        run: |
          npm install
          npm test
