name: Testing

# Remember to detect on prerelease which is a subtype
on: [push, pull_request, release]

# These are going to be our jenkins.yml file
env:
  slack_channel: undefined
  checkmarx_fail_severity: undefined
  checkmarx_warn_severity: undefined
  snyk_fail_severity: undefined
  checkmarx_all_pull_requests: undefined
  app_node_all: undefined
  before_deploy: undefined
  run_front_end_test: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # requires checkout
      # - uses: READ_PACKAGE
      
      - run: npm install
      - run: npm test
      - run: cat package.json | grep version | head -1 | awk -F ':' '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]'

      # - uses: DISPLAY_NAME_CHECK
      # - uses: VERSION_CHECK
      # - uses: OPEN_SOURCE_DEPENDENCY_CHECK
      # - uses: NPM_TEST
      # - uses: NPM_LINT
      # - uses: STATIC_SECURITY_CHECK

      # - uses: POST_TO_PR

      # - uses: DEPLOY_TO_ARTIFACTORY

      # - uses: POSTING_TO_SLACK


