name: Testing

on: [push]

env:
  TEST_VALUE: testing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a script
        run: |
          npm install
          npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a script
        run: echo Hello, world!
      - name: run another script
        run: |
          echo $env.TEST_VALUE
          echo test 2
